[[rule]]
interaction_type = "message"
message_content = '''((?:b|B)lazing(?:ly)*\sfast)'''
points = -1

[[rule]]
interaction_type = "message"
message_content = '''(?:🚀)+.*((?:b|B)lazing(?:ly)*\sfast).*(?:🚀)+'''
points = -2
