[[rule]]
interaction_type = "message"
message_content = '''\b((?:p|P)ython)\b'''
points = 1

[[rule]]
interaction_type = "message"
message_content = '''\b((?:import\s+)?antigravity)\b'''
points = 2

[[rule]]
interaction_type = "message"
message_content = '''(<>|\b[Bb]arry(?:_as_FLUFL)?\b|[Bb][Dd][Ff][Ll]|\b(?:PEP|pep)\s401\b)'''
points = 1

[[rule]]
interaction_type = "message"
message_content = '''\b([Gg]uido(?:\s[Vv]an\s[Rr]ossum)?)\b'''
points = 1
